name: build workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello build"

  startup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello startup"
      
  setup:
    needs: [ build, docker, startup ]
    uses: claudedevops/shared-workflows/.github/workflows/setup.yaml@main
  
  checkov:
    needs: setup
    uses: claudedevops/shared-workflows/.github/workflows/tests.yaml@main
  
  plan:
    needs: checkov
    if: success()
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [ dev, stage, prod ]
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: test.tf
      - run: terraform init
  apply:
    needs: plan
    if: success()
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [ dev, stage, prod ]
    steps:
      - run: echo ${{ matrix.env }}
  
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello docker"
  
  trivy:
    needs: [ docker, setup ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello trivy"
  
  dockerize:
    needs: trivy
    if: success()
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello dockerize"    
