name: build workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello build"
      
  setup:
    needs: [ build, docker ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello setup"
  
  checkov:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello checkov"
  
  plan:
    needs: checkov
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello plan"
  
  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello apply"
  
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello docker"
  
  trivy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello trivy"
