name: build workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello build"
      
  setup:
    needs: [ build, docker ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello setup"
  
  checkov:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello checkov"
  
  plan:
    needs: checkov
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [ dev, stage, prod ]
    steps:
      - run: echo ${{ matrix.env }}
  
  apply:
    needs: plan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [ dev, stage, prod ]
    steps:
      - run: echo ${{ matrix.env }}
  
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello docker"
  
  trivy:
    needs: [ docker, setup ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello trivy"
  
  dockerize:
    needs: trivy
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello dockerize"    
