name: release

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true
        options: [ stage, prod, dev ]

jobs:
  release:
    uses: ./.github/workflows/apply.yaml
    with:
      target-env: ${{ inputs.environment }}
